version: 2
updates:
  # Enable version updates for npm with enhanced security focus
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily" # More frequent for security
      time: "09:00"
      timezone: "UTC"
    open-pull-requests-limit: 10 # Increased for security updates
    reviewers:
      - "yeser-team"
    assignees:
      - "yeser-team"
    commit-message:
      prefix: "deps"
      prefix-development: "deps"
      include: "scope"
    # Enhanced dependency grouping for React Native/Expo apps
    groups:
      # React Native ecosystem
      react-native-core:
        patterns:
          - "react-native"
          - "react"
          - "react-dom"
        update-types:
          - "minor"
          - "patch"
      # Expo and EAS ecosystem
      expo-ecosystem:
        patterns:
          - "expo*"
          - "@expo*"
          - "eas-cli"
        update-types:
          - "minor"
          - "patch"
      # React Native community packages
      react-native-community:
        patterns:
          - "@react-native*"
          - "react-native-*"
        update-types:
          - "patch"
      # Backend services (Supabase, Firebase)
      backend-services:
        patterns:
          - "@supabase*"
          - "supabase*"
          - "@react-native-firebase*"
        update-types:
          - "patch"
      # State management and data fetching
      state-management:
        patterns:
          - "zustand"
          - "@tanstack/react-query*"
          - "@tanstack/query*"
        update-types:
          - "patch"
      # UI and styling
      ui-styling:
        patterns:
          - "react-native-paper"
          - "react-native-vector-icons"
          - "react-native-svg"
          - "moti"
          - "lottie-react-native"
        update-types:
          - "patch"
      # Navigation
      navigation:
        patterns:
          - "@react-navigation*"
          - "react-navigation*"
        update-types:
          - "patch"
      # Development tools
      dev-tools:
        patterns:
          - "eslint*"
          - "@typescript-eslint*"
          - "prettier"
          - "typescript"
          - "@types/*"
        update-types:
          - "patch"
      # Testing frameworks
      testing:
        patterns:
          - "*jest*"
          - "@testing-library*"
          - "babel-jest"
        update-types:
          - "patch"
      # Build and bundling tools
      build-tools:
        patterns:
          - "babel*"
          - "@babel*"
          - "metro*"
        update-types:
          - "patch"
      # Security and validation
      security-validation:
        patterns:
          - "zod"
          - "@hookform*"
          - "react-hook-form"
        update-types:
          - "patch"
    # Enhanced security updates configuration
    security-updates:
      enabled: true
    # Allow automatic merging of patch-level security updates
    allow:
      - dependency-type: "direct"
        update-type: "security"
      - dependency-type: "indirect"
        update-type: "security"
    # Ignore specific packages that might cause issues
    ignore:
      # Ignore major React Native updates (require manual testing)
      - dependency-name: "react-native"
        update-types: ["version-update:semver-major"]
      # Ignore major React updates (require manual testing)
      - dependency-name: "react"
        update-types: ["version-update:semver-major"]
      - dependency-name: "react-dom"
        update-types: ["version-update:semver-major"]
      # Ignore major Expo SDK updates (require migration guides)
      - dependency-name: "expo"
        update-types: ["version-update:semver-major"]

  # Enable version updates for GitHub Actions with security focus
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 5
    commit-message:
      prefix: "ci"
      include: "scope"
    # Group GitHub Actions updates
    groups:
      github-actions:
        patterns:
          - "*"
        update-types:
          - "major"
          - "minor"
          - "patch"
    # Allow automatic security updates for actions
    allow:
      - dependency-type: "direct"
        update-type: "security"

  # Monitor Dockerfile if present
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 3
    commit-message:
      prefix: "docker"

# Global configuration for enhanced security
registries:
  npm-github:
    type: npm-registry
    url: https://npm.pkg.github.com
    token: ${{secrets.GITHUB_TOKEN}} 