version: 2
updates:
  # Enable version updates for npm with enhanced security focus
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily" # More frequent for security
      time: "09:00"
      timezone: "UTC"
    open-pull-requests-limit: 15 # Increased for security updates
    reviewers:
      - "yeser-team"
    assignees:
      - "yeser-team"
    commit-message:
      prefix: "security"
      prefix-development: "deps"
      include: "scope"
    # Enhanced dependency grouping for React Native/Expo apps with security focus
    groups:
      # Security-critical core dependencies
      security-critical:
        patterns:
          - "@react-native-firebase*"
          - "@supabase*"
          - "supabase*"
          - "firebase*"
          - "expo-auth-session"
          - "expo-crypto"
          - "expo-secure-store"
          - "expo-build-properties"
          - "expo-constants"
        update-types:
          - "security"
          - "patch"
          - "minor"
      # React Native ecosystem
      react-native-core:
        patterns:
          - "react-native"
          - "react"
          - "react-dom"
        update-types:
          - "minor"
          - "patch"
      # Expo and EAS ecosystem
      expo-ecosystem:
        patterns:
          - "expo*"
          - "@expo*"
          - "eas-cli"
        update-types:
          - "minor"
          - "patch"
      # React Native community packages
      react-native-community:
        patterns:
          - "@react-native*"
          - "react-native-*"
        update-types:
          - "patch"
      # State management and data fetching
      state-management:
        patterns:
          - "zustand"
          - "@tanstack/react-query*"
          - "@tanstack/query*"
        update-types:
          - "patch"
      # UI and styling
      ui-styling:
        patterns:
          - "react-native-paper"
          - "react-native-vector-icons"
          - "react-native-svg"
          - "moti"
          - "lottie-react-native"
        update-types:
          - "patch"
      # Navigation
      navigation:
        patterns:
          - "@react-navigation*"
          - "react-navigation*"
        update-types:
          - "patch"
      # Development tools and security linting
      dev-security-tools:
        patterns:
          - "eslint*"
          - "@typescript-eslint*"
          - "prettier"
          - "typescript"
          - "@types/*"
          - "eslint-plugin-security"
          - "audit-ci"
        update-types:
          - "patch"
          - "minor"
      # Testing frameworks
      testing:
        patterns:
          - "*jest*"
          - "@testing-library*"
          - "babel-jest"
        update-types:
          - "patch"
      # Build and bundling tools
      build-tools:
        patterns:
          - "babel*"
          - "@babel*"
          - "metro*"
        update-types:
          - "patch"
      # Security and validation libraries
      security-validation:
        patterns:
          - "zod"
          - "@hookform*"
          - "react-hook-form"
          - "validator"
          - "crypto-js"
        update-types:
          - "patch"
          - "minor"
    # Enhanced security updates configuration
    security-updates:
      enabled: true
    # Allow automatic merging of security updates
    allow:
      - dependency-type: "direct"
        update-type: "security"
      - dependency-type: "indirect"
        update-type: "security"
      # Allow automatic patch updates for security-critical packages
      - dependency-name: "@react-native-firebase/*"
        update-type: "patch"
      - dependency-name: "@supabase/*"
        update-type: "patch"
      - dependency-name: "expo-auth-session"
        update-type: "patch"
      - dependency-name: "expo-crypto"
        update-type: "patch"
      - dependency-name: "expo-secure-store"
        update-type: "patch"
    # Ignore specific packages that might cause issues
    ignore:
      # Ignore major React Native updates (require manual testing)
      - dependency-name: "react-native"
        update-types: ["version-update:semver-major"]
      # Ignore major React updates (require manual testing)
      - dependency-name: "react"
        update-types: ["version-update:semver-major"]
      - dependency-name: "react-dom"
        update-types: ["version-update:semver-major"]
      # Ignore major Expo SDK updates (require migration guides)
      - dependency-name: "expo"
        update-types: ["version-update:semver-major"]
      # Ignore major Firebase updates (require configuration changes)
      - dependency-name: "@react-native-firebase/*"
        update-types: ["version-update:semver-major"]

  # Enable version updates for GitHub Actions with security focus
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily" # Daily for security patches
      time: "09:00"
    open-pull-requests-limit: 10
    commit-message:
      prefix: "ci-security"
      include: "scope"
    # Group GitHub Actions updates with security priority
    groups:
      # Security-focused GitHub Actions
      security-actions:
        patterns:
          - "actions/checkout"
          - "actions/setup-node"
          - "actions/upload-artifact"
          - "actions/download-artifact"
          - "github/codeql-action"
        update-types:
          - "major"
          - "minor"
          - "patch"
      # EAS and Expo actions
      eas-expo-actions:
        patterns:
          - "expo/expo-github-action"
        update-types:
          - "major"
          - "minor"
          - "patch"
    # Allow automatic security updates for actions
    allow:
      - dependency-type: "direct"
        update-type: "security"
    # Security-focused ignores
    ignore:
      # Don't auto-update actions that could break CI/CD
      - dependency-name: "expo/expo-github-action"
        update-types: ["version-update:semver-major"]

  # Monitor Dockerfile if present (security-focused)
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "daily" # Daily for security
    open-pull-requests-limit: 5
    commit-message:
      prefix: "docker-security"
    # Allow automatic security updates for Docker
    allow:
      - dependency-type: "direct"
        update-type: "security"
      - dependency-type: "indirect"
        update-type: "security"

# Enhanced global configuration for maximum security
registries:
  # NPM registry configuration (secure by default)
  npm-registry:
    type: npm-registry
    url: https://registry.npmjs.org/
  # GitHub Packages (if using private packages)
  npm-github:
    type: npm-registry
    url: https://npm.pkg.github.com
    token: ${{secrets.GITHUB_TOKEN}}

# Security-focused vulnerability alerts
vulnerability-alerts:
  # Enable automatic security alerts
  enabled: true 